- name: tests
  workspaces:
  - name: source
    workspace: pipeline-workspace
  taskRef:
    name: nose
  params:
  - name: database_uri
    value: "sqlite:///test.db"
  - name: args
  value: "-v --with-spec --spec-color"
  runAfter:
  - clone

spec:
  params: image-registry.openshift-image-registry.svc:5000/$SN_ICR_NAMESPACE/accounts:latest
    - name: build-image

- name: build
 workspaces:
 - name: source
 workspace: pipeline-workspace
 taskRef:
 name: buildah
 kind: ClusterTask
 params:
  - name: IMAGE
  value: "$(params.build-image)"
  runAfter:
  - tests
   - lint
